/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppLogo: typeof import('./components/layout/AppLogo.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    HeroCarousel: typeof import('./components/home/HeroCarousel.vue')['default']
    ImagePicker: typeof import('./components/upload/ImagePicker.vue')['default']
    LocaleSwitcher: typeof import('./components/layout/LocaleSwitcher.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NPagination: typeof import('naive-ui')['NPagination']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    PointCloudViewer: typeof import('./components/tools/PointCloudViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBanner: typeof import('./components/home/SideBanner.vue')['default']
    StepIndicator: typeof import('./components/tools/StepIndicator.vue')['default']
    TaskProgressDisplay: typeof import('./components/tools/TaskProgressDisplay.vue')['default']
    ToolBreadcrumb: typeof import('./components/tools/ToolBreadcrumb.vue')['default']
    ToolCard: typeof import('./components/tools/ToolCard.vue')['default']
    UserMenu: typeof import('./components/layout/UserMenu.vue')['default']
  }
}
