/**
 * Centralized error code catalog.
 * Frontend maps these to i18n keys: `errors.{CODE}`
 */
export const ERROR_CODES = {
  // General
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Auth
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',

  // Rate limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Credits
  CREDITS_INSUFFICIENT: 'CREDITS_INSUFFICIENT',

  // Tools
  TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
  TOOL_INACTIVE: 'TOOL_INACTIVE',
  TOOL_SLUG_EXISTS: 'TOOL_SLUG_EXISTS',
  TOOL_HAS_ACTIVE_TASKS: 'TOOL_HAS_ACTIVE_TASKS',

  // Tool types
  TOOL_TYPE_NOT_FOUND: 'TOOL_TYPE_NOT_FOUND',
  TOOL_TYPE_SLUG_EXISTS: 'TOOL_TYPE_SLUG_EXISTS',
  TOOL_TYPE_HAS_TOOLS: 'TOOL_TYPE_HAS_TOOLS',

  // Tasks
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_CREATION_FAILED: 'TASK_CREATION_FAILED',
  TASK_SERVICE_UNAVAILABLE: 'TASK_SERVICE_UNAVAILABLE',
  TASK_CONFIG_ERROR: 'TASK_CONFIG_ERROR',
  TASK_PROCESSING_FAILED: 'TASK_PROCESSING_FAILED',
  TASK_INPUT_INVALID: 'TASK_INPUT_INVALID',

  // Assets / Uploads
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_SIZE_EXCEEDED: 'UPLOAD_SIZE_EXCEEDED',
  UPLOAD_EXTENSION_MISMATCH: 'UPLOAD_EXTENSION_MISMATCH',
  ASSET_NOT_FOUND: 'ASSET_NOT_FOUND',
  ASSET_FORBIDDEN: 'ASSET_FORBIDDEN',

  // Banners
  BANNER_NOT_FOUND: 'BANNER_NOT_FOUND',

  // Providers
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_SLUG_EXISTS: 'PROVIDER_SLUG_EXISTS',

  // Packages
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // AI Studio
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
  PROVIDER_KEY_DECRYPTION_FAILED: 'PROVIDER_KEY_DECRYPTION_FAILED',
  STORAGE_KEY_INVALID: 'STORAGE_KEY_INVALID',
  URL_GENERATION_FAILED: 'URL_GENERATION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
