/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminHeader: typeof import('./components/layout/AdminHeader.vue')['default']
    AdminSidebar: typeof import('./components/layout/AdminSidebar.vue')['default']
    ConfigFieldRenderer: typeof import('./components/tools/ConfigFieldRenderer.vue')['default']
    DeleteConfirmDialog: typeof import('./components/shared/DeleteConfirmDialog.vue')['default']
    ErrorBoundary: typeof import('./components/shared/ErrorBoundary.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    PageHeader: typeof import('./components/shared/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./components/shared/StatusBadge.vue')['default']
    ThemeSwitcher: typeof import('./components/layout/ThemeSwitcher.vue')['default']
    ToolConfigForm: typeof import('./components/tools/ToolConfigForm.vue')['default']
    TranslationsEditor: typeof import('./components/translations/TranslationsEditor.vue')['default']
  }
}
